### ISSUE TITLE
"Uncaught Invariant Violation: Expected to find a valid target." after cancelling a drag into the react sortable tree

### ISSUE THREAD

**Issue by mx2323** [frontend-collective/react-sortable-tree#490]
# Reporting a Bug?

This is reproducible with one of the examples in the storybook. 

[(https://codesandbox.io/s/xzoq6xprlz]
)
Drag the "baby rabbit" box to the React Sortable Tree area, move it around so that it registers with the React Sortable Tree, then move the box out of the React Sortable Tree area such that the placeholder turns red, then release the box outside of the React Sortable Tree area. 

This will cause the Console to fire with this error. 
```

browser.js:38 Uncaught Invariant Violation: Expected to find a valid target.
    at invariant (https://xzoq6xprlz.codesandbox.io/node_modules/invariant/browser.js:38:15)
    at DragDropMonitorImpl.canDropOnTarget (https://xzoq6xprlz.codesandbox.io/node_modules/dnd-core/lib/cjs/DragDropMonitorImpl.js:67:9)
    at DropTargetMonitorImpl.canDrop (https://xzoq6xprlz.codesandbox.io/node_modules/react-dnd/lib/cjs/DropTargetMonitorImpl.js:24:41)
    at nodeDropTargetPropInjection (https://xzoq6xprlz.codesandbox.io/node_modules/react-sortable-tree/dist/index.cjs.js:2367:28)
    at DragDropContainer.getCurrentState (https://xzoq6xprlz.codesandbox.io/node_modules/react-dnd/lib/cjs/decorateHandler.js:116:29)
    at DragDropContainer._this.handleChange (https://xzoq6xprlz.codesandbox.io/node_modules/react-dnd/lib/cjs/decorateHandler.js:45:39)
    at handleChange (https://xzoq6xprlz.codesandbox.io/node_modules/dnd-core/lib/cjs/DragDropMonitorImpl.js:27:21)
    at dispatch (https://xzoq6xprlz.codesandbox.io/node_modules/redux/lib/redux.js:220:7)
    at Object.eval [as endDrag] (https://xzoq6xprlz.codesandbox.io/node_modules/dnd-core/lib/cjs/DragDropManagerImpl.js:67:21)
    at HTML5Backend.handleTopDragEndCapture (https://xzoq6xprlz.codesandbox.io/node_modules/react-dnd-html5-backend/lib/cjs/HTML5Backend.js:145:31)
```

**Comment by bexoss** [comment]
+1

**Comment by mx2323** [comment]
was able to make a small fix in react-dnd 
https://github.com/react-dnd/react-dnd/issues/1368

**Comment by baddlan** [comment]
+1

**Comment by weirDozzz** [comment]
#740 hope this problem can be solved

**Comment by lewishornsby** [comment]
Is this fixed yet? I really don't want to have to patch a lib :(

**Comment by webspin** [comment]
+1

**Comment by sinanyaman95** [comment]
Is this fixed yet?

**Comment by mepaJanitza** [comment]
it seems to be fixed

**Comment by adkaushik** [comment]
Not fixed yet I guess. Still getting this error

**Comment by samhatoum** [comment]
+1

**Comment by jemliF** [comment]
Not fixed yet

**Comment by karibertils** [comment]
+1 Also getting this

**Comment by NickEmpetvee** [comment]
+1

**Comment by jevy-wangfei** [comment]
+1
