### ISSUE TITLE
Unexpected token export error from react-dnd

### ISSUE THREAD

**Issue by BjoernRave** [frontend-collective/react-sortable-tree#612]
I wanted to use this library as it looks very nice and extensive, but when including it in my next.js project I encountered the following error:
```
/Users/bjoern/projects/compendium2/frontend/node_modules/react-dnd/dist/esm/index.js:1
export * from './common';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/bjoern/projects/compendium2/frontend/node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js:24:17)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/bjoern/projects/compendium2/frontend/node_modules/react-sortable-tree/dist/index.cjs.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
```

**Comment by b-ponomarenko** [comment]
I have the same error :(

**Comment by b-ponomarenko** [comment]
Try to use `2.6.2`

**Comment by alexandregiordanelli** [comment]
same here

**Comment by yanngdev** [comment]
Same here, had to go back to `2.6.2`.

**Comment by wsalazar-peakactivity** [comment]
I went back to 2.6.2 and I'm still experiencing this issue. Thoughts?
